config/routes.rb
Galleror::Application.routes.draw do
  devise_for :users
  resources :albums do
    resources :photos
    resources :votes, only: [:create, :destroy]
  end

  root 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :votes

  validates :title, presence: true
  validates :rating, numericality: { only_integer: true, allow_blank: true,
    greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  scope :public, -> { where(public: true) }

  after_initialize :set_default_values, if: :new_record?

  protected

  def set_default_values
    self.public = true if public.nil?
    self.rating = 1 if rating.blank?
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  mount_uploader :file, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  respond_to :html

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.public
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @photos = @album.photos
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.create(album_params.merge(user_id: current_user.id))
    respond_with(@album, location: albums_url)
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    @album.update(album_params)
    respond_with(@album, location: albums_url)
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_with(@album)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :description, :public, :rating)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_album
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  respond_to :html

  # GET /photos
  # GET /photos.json
  def index
    @photos = @album.photos
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = @album.photos.build
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = @album.photos.create(photo_params)
    respond_with(@photo, location: @album)
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    @photo.update(photo_params)
    respond_with(@photo, location: @album)
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_with(@photo, location: @album)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def set_album
      @album = Album.find(params[:album_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :file, :album_id)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :set_album

  respond_to :js

  def create
    @album.votes.create(user_id: current_user.id)
    render 'update'
  end

  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy
    render 'update'
  end

  protected

  def set_album
    @album = Album.find(params[:album_id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def format_rating(rating, image = 'face-star.png')
    stars = image_tag(image, alt: '*') * rating
    content_tag :span, stars.html_safe, class: 'rating'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/albums/_album.html.erb
<tr>
  <td><%= album.title %></td>
  <td><%= format_rating(album.rating) %></td>
  <td><%= link_to 'Add photo', new_album_photo_path(album) %></td>
  <td><%= link_to 'Show', album %></td>
  <td><%= link_to 'Edit', edit_album_path(album) %></td>
  <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/albums/_album_photo.html.erb
<li>
  <%= link_to image_tag(photo.file.url(:thumb)), photo.file.url %>
  <%= photo.title %>
  <%= link_to 'Show', album_photo_path(photo.album, photo) %> |
  <%= link_to 'Edit', edit_album_photo_path(photo.album, photo) %> |
  <%= link_to 'Destroy', [photo.album, photo], method: :delete, confirm: 'Are you sure?' %>
</li>

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, size: '80x4' %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating, size: 3, maxlength: 1 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/_votes.html.erb
<p>
  <strong>Votes:</strong>
  <%= @album.votes.size %>
  <% if user_signed_in? %>
    <% if vote = @album.votes.find_by_user_id(current_user.id) %>
      <%= link_to 'Un-vote!', album_vote_path(@album, vote), method: :delete, remote: true %>
    <% else %>
      <%= link_to 'Vote!', album_votes_path(@album), method: :post, remote: true %>
    <% end %>
  <% end %>
</p>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Rating</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @albums %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @album.user.try(:email) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<p>
  <strong>Public:</strong>
  <%= @album.public %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @album.rating %>
</p>

<div class="votes">
  <%= render 'votes' %>
</div>

<ul>
  <%= render partial: 'album_photo', collection: @photos, as: 'photo' %>
</ul>

<%= link_to 'Add photo', new_album_photo_path(@album) %> |
<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GalleRoR</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="login">
  <% if user_signed_in? %>
    <span class="user">Signed in as <%= current_user.email %></span> |
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign in', new_user_session_path %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for([@album, @photo]) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<li><%= photo.title %></li>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Back to albums list', albums_path %> |
<%= link_to 'Back to album page', @album %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>File</th>
      <th>Album</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.title %></td>
        <td>
          <%= image_tag(photo.file.url(:thumb)) %>
        </td>
        <td>
          <% if photo.album %>
            <%= link_to photo.album.title, photo.album %>
          <% end %>
        </td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back to albums list', albums_path %> |
<%= link_to 'Back to album page', @album %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @photo.title %>
</p>

<p>
  <strong>Album:</strong>
  <%= @photo.album.try(:title) %>
</p>

<p>
  <strong>File:</strong>
  <%= link_to(image_tag(@photo.file.url(:thumb)), @photo.file.url) %>
</p>

<%= link_to 'Edit', edit_album_photo_path(@album, @photo) %> |
<%= link_to 'Back to album', @album %>

app/views/votes/update.js.erb
$('div.votes').html('<%= escape_javascript render(partial: 'albums/votes') %>');